# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение датчиков
GET {{baseUrl}}/sensors/
Content-Type: application/json

###

# создание датчика
POST {{baseUrl}}/sensors/
Content-Type: application/json

{
  "name": "ESP43",
  "description": "sensor 43"
}

###

# обновление датчика
PATCH {{baseUrl}}/sensors/17/
Content-Type: application/json

{
  "description": "xcracked sensor 17"
}

###

# получение информации по датчику
GET {{baseUrl}}/sensors/17/
Content-Type: application/json

###

# добавление измерения
POST {{baseUrl}}/measurements/
Content-Type: application/json

{
  "sensor": 17,
  "temperature": 12.3
}